name: 🚨 Bug report
title: "bug: "
description: Create a bug report to help us improve
labels: ["bug/fix", "needs: triage"]

body:
  - type: input
    attributes:
      label: Version
      description: |
        Let us know which version of the CLI you are using. Just run `npx capawesome --version` to get the version number. Please make sure you are using the latest version before reporting an issue. Chances are that the bug you discovered has already been fixed in a subsequent version.
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour using the provided example.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other information
      description: List any other information that is relevant to your issue. Operating system, Node.js version, etc.
  - type: checkboxes
    attributes:
      label:  Before submitting 
      description: |
        A well-written bug report allows the maintainers to quickly recreate the necessary conditions to inspect the bug and quickly find its root cause.
        Please ensure your bug report fulfills all of the following requirements.
      options:
      - label: I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
        required: true
      - label: I have attached links to possibly related issues and discussions.
        required: true
      - label: I understand that incomplete issues (e.g. without reproduction) are closed.
        required: true
