import jobsService from '@/services/jobs.js';
import { isInteractive } from '@/utils/environment.js';
import { prompt } from '@/utils/prompt.js';
import consola from 'consola';

/**
 * Request an AI-powered failure summary for a failed job and print it.
 *
 * Powered by Capawesome Cloud Assist. The summary is printed as plain text so
 * the terminal can soft-wrap it to any width.
 */
export const printJobFailureSummary = async (options: { jobId: string }): Promise<void> => {
  const { jobId } = options;
  consola.start('Generating failure summary with Capawesome Cloud Assist...');
  const { summary } = await jobsService.generateFailureSummary({ jobId });
  consola.success('Failure summary generated by Capawesome Cloud Assist:');
  console.log();
  console.log(summary);
};

/**
 * Best-effort variant of {@link printJobFailureSummary}.
 *
 * Warns instead of throwing so that it never masks the underlying job failure.
 */
const tryPrintJobFailureSummary = async (options: { jobId: string }): Promise<void> => {
  try {
    await printJobFailureSummary(options);
  } catch {
    consola.warn('Could not generate a failure summary at this time.');
  }
};

/**
 * Offer an AI-powered failure summary after a job has failed.
 *
 * - If the summary was requested up front, it is generated right away.
 * - Otherwise, the user is asked whether they want one (interactive), or
 *   pointed to the command that generates it (non-interactive).
 */
export const offerJobFailureSummary = async (options: {
  jobId: string;
  requested: boolean;
  command: string;
}): Promise<void> => {
  const { jobId, requested, command } = options;
  if (requested) {
    await tryPrintJobFailureSummary({ jobId });
    return;
  }
  if (isInteractive()) {
    // @ts-ignore wait till https://github.com/unjs/consola/pull/280 is merged
    const wantsSummary = await prompt('Do you want Capawesome Cloud Assist to explain what went wrong?', {
      type: 'confirm',
      initial: false,
    });
    if (wantsSummary) {
      await tryPrintJobFailureSummary({ jobId });
    }
  } else {
    consola.info(`Need help? Run \`${command}\` for an AI-powered failure summary.`);
  }
};
