name: Test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      cli_version:
        description: "Capawesome CLI version"
        required: false
        default: "latest"
        type: string
  release:
    types: [published]

env:
  BUNDLE_PATH: www
  BUNDLE_URL: https://api.cloud.capawesome.io/v1/apps/08c68ab0-e51c-4504-aa51-70b949577e46/bundles/3866d9a6-7a2c-4c5d-832c-e36bdc5f6239/download
  CAPAWESOME_CLOUD_APP_ID: 08c68ab0-e51c-4504-aa51-70b949577e46

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download sample bundle
        run: curl -sS -L ${{ env.BUNDLE_URL }} --output ${{ env.BUNDLE_PATH }}.zip
      - name: Unzip the bundle
        run: unzip ${{ env.BUNDLE_PATH }}.zip
      - name: Install Capawesome CLI version
        run: npm i -g @capawesome/cli@3.2.1-dev.edc7dde.1759002886
      - name: Login to Capawesome CLI
        run: capawesome login --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
      - name: Check who is logged in
        run: npx capawesome whoami
      - name: Create a bundle
        run: npx capawesome apps:bundles:create --app-id ${{ env.CAPAWESOME_CLOUD_APP_ID }} --path ${{ env.BUNDLE_PATH }}
