name: Test

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

env:
  BUNDLE_PATH: www
  BUNDLE_URL: https://api.cloud.capawesome.io/v1/apps/08c68ab0-e51c-4504-aa51-70b949577e46/bundles/3866d9a6-7a2c-4c5d-832c-e36bdc5f6239/download
  CAPAWESOME_CLOUD_APP_ID: 08c68ab0-e51c-4504-aa51-70b949577e46

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node-version: [18, 20, 22]
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download sample bundle
        run: curl -sS -L ${{ env.BUNDLE_URL }} --output ${{ env.BUNDLE_PATH }}.zip
      - name: Unzip the bundle
        run: unzip ${{ env.BUNDLE_PATH }}.zip
      - name: Install latest Capawesome CLI version
        run: npm i -g @capawesome/cli@latest
      - name: Login to Capawesome CLI
        run: capawesome login --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
      - name: Check who is logged in
        run: npx capawesome whoami
      - name: Create a channel
        run: |
          npx capawesome apps:channels:create \
          --app-id ${{ env.CAPAWESOME_CLOUD_APP_ID }} \
          --name test-${{ matrix.os }}-${{ matrix.node-version }} \
          --ignore-errors
      - name: Generate a manifest file
        run: |
          npx capawesome manifests:generate \
          --path ${{ env.BUNDLE_PATH }}
      - name: Create a bundle
        run: |
          npx capawesome apps:bundles:create \
          --app-id ${{ env.CAPAWESOME_CLOUD_APP_ID }} \
          --channel test-${{ matrix.os }}-${{ matrix.node-version }} \
          --path ${{ env.BUNDLE_PATH }}
      - name: Delete the channel
        run: |
          npx capawesome apps:channels:delete \
          --app-id ${{ env.CAPAWESOME_CLOUD_APP_ID }} \
          --name test-${{ matrix.os }}-${{ matrix.node-version }}
